# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, release/*]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      #Node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      #Node   
      - name: Run Node
        run: node index.html

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Heroku    
      - name: Heroku Action
        uses: CDNievas/heroku-action@v1.0
        with:
          heroku_email: "baobaoack000@gmail.com"
          heroku_api_key: ${{secrets."0a3efa20-0a3efa20a3efa2"}}
          heroku_app_name: "myheroku-new01"
          useforce: true,
          dynamicFiles: true,
          procfile: "worker: npm start",
          buildpacks: "['https://github.com/heroku/heroku-buildpack-nodejs.git']"

